export enum StimErrorCode {
  STIM_INEXISTANTE = 'JOAPI_STIM_0001',
  AUCUN_CLIENT = 'JOAPI_STIM_0002',
  CLIENT_INTERDIT = 'JOAPI_STIM_0003',
  STATUT_INVALIDE = 'JOAPI_STIM_0004',
  CLOTUREE = 'JOAPI_STIM_0005',
  NOMBRE_UTILISATION = 'JOAPI_STIM_0006',
  PERIODE_VALIDITE = 'JOAPI_STIM_0007',
  ETABLISSEMENT_UTILISATION = 'JOAPI_STIM_0008',
  DELAI_UTILISATION = 'JOAPI_STIM_0009',
  ETABLISSEMENT_UTILISATION_NULL = 'JOAPI_STIM_0011',
  PERIODE_NULL = 'JOAPI_STIM_0012',
  ETABLISSEMENT_CONSOMMATION_INCONNU = 'JOAPI_STIM_0013',
  NON_HABILITE = 'JOAPI_STIM_0017',
  API_COMMUNICATION_ERROR = 'API_COMMUNICATION_ERROR',
}

export enum MboxErrorCode {
  MBOX_AUTH_ERROR = 'MBOX_AUTH_ERROR',
  PIN_INVALID = 'PIN_INVALID',
  MBOX_TIMEOUT_ERROR = 'MBOX_TIMEOUT_ERROR',
}

export enum ApplicationErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  APPLICATION_ERROR = 'APPLICATION_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
